import React from "react";
import Head from "next/head";
import HeaderNab from "../components/common/HeaderNab";
import FooterOne from "./FooterOne";
import ShoppingCart from "./ShoppingCart";
import MobileMenu from "./MobileMenu";
import ProductModal from "./ProductModal";
function Layout({ children, title = "Next.js Ecommerce" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* Header Nab   */}
      <HeaderNab />
      <div id="content">
        {children}
        {/* FooterOne */}
        <FooterOne />
        {/* ShoppingCart  */}
        <ShoppingCart />
        {/* MobileMenu  */}
        <MobileMenu />
        {/* ProductModal  */}
        <ProductModal />
      </div>
    </>
  );
}

export default Layout;
