import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeaderNab from "../components/common/HeaderNab";
import Slider from "../components/home/Slider";
import IntroductionOne from "../components/home/IntroductionOne";
import IntroductionTwo from "../components/home/IntroductionTwo";
import ProductSlider from "../components/home/ProductSlider";
import Testimonial from "../components/home/Testimonial";
import TeamOne from "../components/home/TeamOne";
import BookService from "../components/home/BookService";
import FooterOne from "../components/home/FooterOne";
import Section1 from "../components/home/Section1";
import Section2 from "../components/home/Section2";
import Modal from "../components/home/Modal";
import Script from "next/script";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* Header Nab   */}
      <HeaderNab />
      <div id="content">
        {/* Slider */}
        <Slider />
        {/* IntroductionOne  */}
        <IntroductionOne />
        {/* IntroductionTwo  */}
        <IntroductionTwo />
        {/* ProductSlider  */}
        <ProductSlider />
        {/* Testimonial  */}
        <Testimonial />
        {/* TeamOne  */}
        <TeamOne />
        {/* BookService */}
        <BookService />
        {/* FooterOne */}
        <FooterOne />
        {/* Section1  */}
        <Section1 />
        {/* Section2  */}
        <Section2 />
        {/* Modal  */}
        <Modal />
      </div>
      {/* <Script
        src="/app/assets/js/main.js"
        onLoad={() => {
          runHeroSliderAnimation();
          slickSlider();
          openSearchBox();
          onOpenDrawer();
          mobileSidebarMenuHandle();
          onOpenQuickViewModal();
        }}
      /> */}
    </>
  );
}
