import React from "react";
import Head from "next/head";
import HeaderNab from "../components/common/HeaderNab";
import FooterOne from "../components/home/FooterOne";
import Products from "../components/shop/Products";
function shop() {
  return (
    <>
      <Head>
        <title>Create Shop Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* Header Nab   */}
      <HeaderNab />
      <div id="content">
        <div className="breadcrumb">
          <div className="container">
            <h2>Shop</h2>
            <ul>
              <li>Home</li>
              <li className="active">Shop</li>
            </ul>
          </div>
        </div>
        <Products />
        {/* FooterOne */}
        <FooterOne />
      </div>
    </>
  );
}

export default shop;
